import type { Language } from "@/i18n/translations";

const ru = {
  hubTitle: "Презентации с ИИ",
  hubSubtitle: "Сначала утвердите понятный план, затем получите готовые слайды. Выберите формат под свою задачу.",
  newPresentation: "Новая презентация",
  classicTitle: "Классическая презентация",
  classicDescription: "Аккуратные учебные слайды, которые можно редактировать в PowerPoint.",
  classicFeatureOne: "Текст, таблицы и схемы остаются редактируемыми",
  classicFeatureTwo: "Единая тема и проверенная компоновка",
  classicFeatureThree: "PPTX для дальнейшей работы",
  creativeTitle: "Творческая презентация",
  creativeDescription: "Каждый слайд рисуется ИИ целиком — ярко, необычно и в одном стиле.",
  creativeFeatureOne: "Уникальная композиция каждого слайда",
  creativeFeatureTwo: "Иллюстрации, подписи и схемы в одном изображении",
  creativeFeatureThree: "Текст внутри слайда не редактируется",
  chooseClassic: "Создать классическую",
  chooseCreative: "Создать творческую",
  recentTitle: "Мои презентации",
  recentSubtitle: "Черновики и готовые работы сохраняются автоматически.",
  emptyTitle: "Здесь появятся ваши презентации",
  emptyDescription: "Выберите один из двух режимов выше — система проведёт вас по шагам.",
  loading: "Загрузка…",
  retry: "Повторить",
  delete: "Удалить",
  open: "Открыть",
  continue: "Продолжить",
  created: "Создано",
  slides: "слайдов",
  deleteTitle: "Удалить презентацию?",
  deleteBody: "Презентация и все её версии будут удалены. Это действие нельзя отменить.",
  cancel: "Отмена",
  confirmDelete: "Да, удалить",
  modeClassic: "Классическая",
  modeCreative: "Творческая",
  statusDraft: "Черновик",
  statusPlanning: "Создаём план",
  statusPlanReady: "План готов",
  statusApproved: "План утверждён",
  statusGenerating: "Создаём слайды",
  statusReview: "Нужна проверка",
  statusReady: "Готово",
  statusFailed: "Есть ошибка",
  statusCancelled: "Остановлено",
  stepSetup: "Настройки",
  stepPlan: "План",
  stepGenerate: "Создание",
  stepReview: "Проверка",
  backToPresentations: "К презентациям",
  setupTitle: "Расскажите, какая презентация нужна",
  setupSubtitle: "Заполните основные поля. Дополнительные настройки можно раскрыть ниже.",
  topic: "Тема презентации",
  topicPlaceholder: "Например: Компьютер жады, 7 класс",
  subject: "Предмет",
  subjectPlaceholder: "Информатика",
  grade: "Класс или аудитория",
  gradePlaceholder: "7 класс",
  language: "Язык слайдов",
  slideCount: "Количество слайдов",
  source: "На чём основываться",
  sourceScratch: "С нуля",
  sourceLesson: "По плану урока",
  sourceMaterials: "По материалам",
  sourceText: "План или исходный материал",
  sourceTextPlaceholder: "Вставьте сюда план урока, основные тезисы или текст материала…",
  goals: "Цели урока",
  goalsPlaceholder: "Что ученики должны понять или уметь после урока?",
  textDensity: "Количество текста",
  densityVisual: "Мало текста",
  densityBalanced: "Баланс",
  densityDetailed: "Подробно",
  style: "Визуальный стиль",
  styleClean: "Спокойный учебный",
  styleBright: "Яркая инфографика",
  styleWarm: "Тёплый иллюстративный",
  styleMinimal: "Минимализм",
  customStyle: "Своё описание стиля",
  customStylePlaceholder: "Например: светлый фон, синие и оранжевые акценты, дружелюбные 3D-иллюстрации",
  moreSettings: "Дополнительные настройки",
  instructions: "Дополнительные пожелания",
  instructionsPlaceholder: "Например: добавьте два задания и итоговую рефлексию",
  createPlan: "Создать план",
  creatingPlan: "Создаём проект…",
  creativeNoticeTitle: "Как работает творческий режим",
  creativeNoticeBody: "После утверждения плана ИИ нарисует каждый слайд целиком. Текст внутри картинки нельзя будет изменить в PowerPoint.",
  required: "Заполните обязательное поле",
  genericError: "Не удалось выполнить действие. Попробуйте ещё раз.",
  connectionError: "Не удалось связаться с сервисом. Проверьте интернет и попробуйте ещё раз — ваши данные сохранены.",
  sessionError: "Сессия завершилась. Войдите снова и продолжите работу.",
  permissionError: "Для этого действия недостаточно прав.",
  notFoundError: "Эта презентация больше недоступна. Вернитесь к списку презентаций.",
  rateLimitError: "Сейчас слишком много запросов. Подождите немного и попробуйте ещё раз.",
  paymentError: "На балансе недостаточно монет для создания слайдов.",
  invalidInputError: "Проверьте заполненные поля и попробуйте ещё раз.",
  planTitle: "Проверьте план презентации",
  planSubtitle: "Измените порядок, формулировки и содержание. Слайды начнут создаваться только после вашего подтверждения.",
  planGenerating: "ИИ составляет план…",
  planGeneratingHint: "Можно закрыть страницу и вернуться позже — работа продолжится.",
  planNotStarted: "План ещё не запущен",
  startPlan: "Создать план",
  planFailed: "План пока не готов",
  planFailureHint: "Ваши настройки сохранены. Попробуйте ещё раз — заполнять всё заново не нужно.",
  regeneratePlan: "Попробовать ещё раз",
  planRetrying: "Пробуем ещё раз…",
  planAutoRetrying: "Первый запуск не завершился. Мы уже пробуем восстановить план — заполнять форму заново не нужно.",
  planRetryUnavailable: "Не удалось запустить повтор. Проверьте интернет и попробуйте ещё раз — ваши настройки сохранены.",
  planStatusUnavailable: "Проверяем готовность плана",
  planStatusHint: "Работа могла продолжиться в фоне. Обновите статус — новый план при этом не запускается.",
  checkPlanStatus: "Обновить статус",
  presentationTitle: "Название презентации",
  styleAnchor: "Общий стиль",
  styleAnchorPlaceholder: "Единая палитра и визуальный язык всей презентации",
  slide: "Слайд",
  slideTitle: "Заголовок",
  slidePurpose: "Задача слайда",
  slideBody: "Основное содержание",
  slideBullets: "Тезисы — по одному в строке",
  slideType: "Тип слайда",
  visualIdea: "Что показать на слайде",
  exactText: "Точный текст на слайде — по одному элементу в строке",
  facts: "Обязательные факты — по одному в строке",
  imagePrompt: "Подробное задание для изображения",
  speakerNotes: "Заметки учителя",
  advancedPrompt: "Задание для ИИ",
  moveUp: "Переместить выше",
  moveDown: "Переместить ниже",
  duplicate: "Дублировать",
  deleteSlide: "Удалить слайд",
  addSlide: "Добавить слайд",
  unsaved: "Есть несохранённые изменения",
  saving: "Сохраняем…",
  saved: "Все изменения сохранены",
  saveDraft: "Сохранить",
  calculateCost: "Рассчитать стоимость",
  costTitle: "Стоимость генерации",
  costPending: "Рассчитываем…",
  costPerSlide: "за один слайд",
  costTotal: "всего",
  coins: "монет",
  approveAndGenerate: "Утвердить план и создать слайды",
  approvedPlanReadOnly: "План уже утверждён и доступен только для просмотра.",
  backToEditor: "Вернуться к слайдам",
  approveTitle: "Начать создание слайдов?",
  approveClassicBody: "План будет зафиксирован. После генерации текст и оформление можно будет изменить в редакторе.",
  approveCreativeBody: "План будет зафиксирован, а каждый слайд — нарисован целиком. Повторная генерация отдельного слайда оплачивается отдельно.",
  approve: "Утвердить и начать",
  revisionConflict: "План изменился в другой вкладке. Обновите страницу, чтобы не потерять новую версию.",
  planValidation: "Заполните названия всех слайдов. Допустимо 4–30 слайдов, до 16 пунктов и до 20 фактов или строк точного текста на слайд.",
  editorTitle: "Презентация",
  generationProgress: "Создание слайдов",
  generatedOf: "готово",
  jobQueued: "В очереди",
  jobRunning: "Генерируется",
  jobCompleted: "Генерация завершена",
  jobFailed: "Генерация завершилась с ошибкой",
  jobCompletedHint: "Слайды готовы. Проверьте их перед скачиванием.",
  jobPartialHint: "Большинство слайдов готово. Откройте отмеченный слайд и создайте его заново.",
  jobFailedHint: "Ваш план и готовые слайды сохранены. Можно повторить создание.",
  jobCancelledHint: "Создание остановлено. Уже готовые слайды сохранены.",
  stopGeneration: "Остановить оставшиеся",
  stopping: "Останавливаем…",
  refreshSafe: "Можно закрыть страницу — прогресс сохранится.",
  selectedSlide: "Выбранный слайд",
  selectSlide: "Выберите слайд",
  waitingSlide: "Этот слайд ещё создаётся",
  failedSlide: "Этот слайд не получился",
  failedSlideHelp: "Нажмите «Создать слайд заново» — остальные слайды останутся без изменений.",
  retryFailedSlide: "Создать слайд заново",
  openFailedSlide: "Открыть проблемный слайд",
  exportBlocked: "Скачивание станет доступно, когда все слайды будут готовы.",
  generationNotFinished: "Дождитесь завершения создания слайдов.",
  previewUnavailable: "Предпросмотр пока недоступен",
  provisionalPreview: "Черновой предпросмотр",
  layout: "Компоновка",
  layoutAuto: "Автоматически",
  layoutTitle: "Титульный",
  layoutSection: "Раздел",
  layoutContent: "Текст и пункты",
  layoutTitleBody: "Заголовок и текст",
  layoutTwoColumns: "Две колонки",
  layoutComparison: "Сравнение",
  layoutTimeline: "Хронология",
  layoutProcess: "Процесс",
  layoutCards: "Карточки",
  layoutDiagram: "Схема",
  layoutTable: "Таблица",
  layoutQuiz: "Вопрос",
  layoutSummary: "Итоги",
  theme: "Цвета",
  themeSand: "Тёплые",
  themeOcean: "Синие",
  themeForest: "Зелёные",
  themeNight: "Тёмные",
  body: "Основной текст",
  bullets: "Тезисы",
  notes: "Заметки выступающего",
  autosaveOn: "Изменения сохраняются автоматически",
  saveError: "Не удалось сохранить изменения",
  versions: "Варианты",
  version: "Вариант",
  activeVersion: "Выбран",
  useVersion: "Выбрать",
  regenerate: "Создать другой вариант",
  regenerating: "Запускаем…",
  rebuildSlide: "Создать слайд заново",
  regenerationInstruction: "Что изменить в новом варианте",
  regenerationInstructionPlaceholder: "Например: меньше текста, крупнее схема, спокойнее цвета…",
  acceptSlide: "Принять слайд",
  accepted: "Слайд принят",
  qaTitle: "Проверка текста",
  qaClean: "Обязательный текст найден, критических замечаний нет.",
  qaWarning: "Проверьте этот фрагмент перед экспортом",
  qaTextWarning: "Автопроверка не смогла подтвердить весь текст. Сверьте надписи на слайде.",
  qaLayoutWarning: "Проверьте, что слайд полностью помещается на экране и ничего не обрезано.",
  qaColorWarning: "Проверьте контраст и читаемость текста на фоне.",
  qaGenericWarning: "Автопроверка нашла место, которое стоит просмотреть вручную.",
  exactTextWarning: "ИИ может допустить опечатку — внимательно проверьте текст на изображении.",
  export: "Экспорт",
  exportTitle: "Скачать презентацию",
  exportSubtitle: "Выберите, что скачать.",
  exportFormat: "Формат",
  exportVariant: "Вариант",
  editablePptx: "Редактируемый PowerPoint",
  pixelPerfectPptx: "Точное совпадение",
  imagePresentation: "PowerPoint",
  exportPowerPointDescription: "Текст, таблицы и элементы можно менять в PowerPoint.",
  exportCreativePowerPointDescription: "Слайды сохранят свой вид; каждый слайд останется картинкой.",
  exportPdfLabel: "PDF",
  exportCreativeNotice: "В творческой презентации каждый слайд остаётся одной картинкой.",
  exportPdfNotice: "Удобно отправить или распечатать. Изменять слайды нельзя.",
  exportSlidesNotReady: "Один из слайдов ещё не готов. Вернитесь к слайдам, откройте отмеченный красным и нажмите «Создать слайд заново», затем повторите скачивание.",
  exportReturnToSlides: "Вернуться к слайдам",
  startExport: "Подготовить файл",
  preparingExport: "Подготавливаем…",
  exportQueuedHint: "Файл готовится. Это окно можно закрыть — готовый файл появится здесь автоматически.",
  readyFiles: "Готовые файлы",
  download: "Скачать",
  close: "Закрыть",
  noExports: "Готовых файлов пока нет",
  partialFailure: "Часть слайдов требует внимания",
  returnToPlan: "Вернуться к плану",
  previous: "Назад",
  next: "Далее",
} as const;

export type PresentationCopy = { [K in keyof typeof ru]: string };

const kk: PresentationCopy = {
  hubTitle: "ЖИ презентациялар",
  hubSubtitle: "Алдымен түсінікті жоспарды бекітіңіз, содан кейін дайын слайдтарды алыңыз. Міндетіңізге сай форматты таңдаңыз.",
  newPresentation: "Жаңа презентация",
  classicTitle: "Классикалық презентация",
  classicDescription: "PowerPoint ішінде өңдеуге болатын жинақы оқу слайдтары.",
  classicFeatureOne: "Мәтін, кесте және сызбалар өңделеді",
  classicFeatureTwo: "Біртұтас тақырып және тексерілген орналасу",
  classicFeatureThree: "Әрі қарай жұмыс істеуге арналған PPTX",
  creativeTitle: "Шығармашылық презентация",
  creativeDescription: "Әр слайдты ЖИ тұтас салады — жарқын, ерекше және бір стильде.",
  creativeFeatureOne: "Әр слайдтың бірегей композициясы",
  creativeFeatureTwo: "Иллюстрация, жазу және сызба бір суретте",
  creativeFeatureThree: "Сурет ішіндегі мәтін өңделмейді",
  chooseClassic: "Классикалық жасау",
  chooseCreative: "Шығармашылық жасау",
  recentTitle: "Менің презентацияларым",
  recentSubtitle: "Жобалар мен дайын жұмыстар автоматты түрде сақталады.",
  emptyTitle: "Презентацияларыңыз осында пайда болады",
  emptyDescription: "Жоғарыдағы екі режимнің бірін таңдаңыз — жүйе сізді қадамдар бойынша жүргізеді.",
  loading: "Жүктелуде…",
  retry: "Қайталау",
  delete: "Жою",
  open: "Ашу",
  continue: "Жалғастыру",
  created: "Жасалған",
  slides: "слайд",
  deleteTitle: "Презентация жойылсын ба?",
  deleteBody: "Презентация және оның барлық нұсқасы жойылады. Бұл әрекетті қайтару мүмкін емес.",
  cancel: "Бас тарту",
  confirmDelete: "Иә, жою",
  modeClassic: "Классикалық",
  modeCreative: "Шығармашылық",
  statusDraft: "Жоба",
  statusPlanning: "Жоспар жасалуда",
  statusPlanReady: "Жоспар дайын",
  statusApproved: "Жоспар бекітілді",
  statusGenerating: "Слайдтар жасалуда",
  statusReview: "Тексеру қажет",
  statusReady: "Дайын",
  statusFailed: "Қате бар",
  statusCancelled: "Тоқтатылды",
  stepSetup: "Баптау",
  stepPlan: "Жоспар",
  stepGenerate: "Жасау",
  stepReview: "Тексеру",
  backToPresentations: "Презентацияларға",
  setupTitle: "Қандай презентация керек екенін жазыңыз",
  setupSubtitle: "Негізгі өрістерді толтырыңыз. Қосымша баптауларды төменде ашуға болады.",
  topic: "Презентация тақырыбы",
  topicPlaceholder: "Мысалы: Компьютер жады, 7-сынып",
  subject: "Пән",
  subjectPlaceholder: "Информатика",
  grade: "Сынып немесе аудитория",
  gradePlaceholder: "7-сынып",
  language: "Слайд тілі",
  slideCount: "Слайд саны",
  source: "Неге сүйену керек",
  sourceScratch: "Нөлден",
  sourceLesson: "Сабақ жоспары бойынша",
  sourceMaterials: "Материалдар бойынша",
  sourceText: "Жоспар немесе бастапқы материал",
  sourceTextPlaceholder: "Сабақ жоспарын, негізгі тезистерді немесе материал мәтінін енгізіңіз…",
  goals: "Сабақ мақсаттары",
  goalsPlaceholder: "Оқушылар сабақтан кейін нені түсінуі немесе істей алуы керек?",
  textDensity: "Мәтін мөлшері",
  densityVisual: "Мәтін аз",
  densityBalanced: "Теңгерім",
  densityDetailed: "Толық",
  style: "Көрнекі стиль",
  styleClean: "Тыныш оқу стилі",
  styleBright: "Жарқын инфографика",
  styleWarm: "Жылы иллюстрация",
  styleMinimal: "Минимализм",
  customStyle: "Стильді өзіңіз сипаттаңыз",
  customStylePlaceholder: "Мысалы: ашық фон, көк және қызғылт сары екпіндер, достық 3D иллюстрациялар",
  moreSettings: "Қосымша баптаулар",
  instructions: "Қосымша тілектер",
  instructionsPlaceholder: "Мысалы: екі тапсырма және қорытынды рефлексия қосыңыз",
  createPlan: "Жоспар құру",
  creatingPlan: "Жоба жасалуда…",
  creativeNoticeTitle: "Шығармашылық режим қалай жұмыс істейді",
  creativeNoticeBody: "Жоспар бекітілгеннен кейін ЖИ әр слайдты тұтас салады. Сурет ішіндегі мәтінді PowerPoint-та өзгерту мүмкін емес.",
  required: "Міндетті өрісті толтырыңыз",
  genericError: "Әрекетті орындау мүмкін болмады. Қайталап көріңіз.",
  connectionError: "Қызметпен байланысу мүмкін болмады. Интернетті тексеріп, қайта көріңіз — деректеріңіз сақталды.",
  sessionError: "Сеанс аяқталды. Қайта кіріп, жұмысты жалғастырыңыз.",
  permissionError: "Бұл әрекетті орындауға рұқсат жеткіліксіз.",
  notFoundError: "Бұл презентация енді қолжетімсіз. Презентациялар тізіміне оралыңыз.",
  rateLimitError: "Қазір сұраныс көп. Сәл күтіп, қайта көріңіз.",
  paymentError: "Слайдтарды жасауға баланста монета жеткіліксіз.",
  invalidInputError: "Толтырылған өрістерді тексеріп, қайта көріңіз.",
  planTitle: "Презентация жоспарын тексеріңіз",
  planSubtitle: "Ретін, тұжырымдарын және мазмұнын өзгертіңіз. Слайдтар тек сіз растағаннан кейін жасалады.",
  planGenerating: "ЖИ жоспар құрып жатыр…",
  planGeneratingHint: "Бетті жауып, кейін оралуға болады — жұмыс жалғасады.",
  planNotStarted: "Жоспар әлі іске қосылмаған",
  startPlan: "Жоспар құру",
  planFailed: "Жоспар әзірше дайын емес",
  planFailureHint: "Баптауларыңыз сақталды. Қайта жасап көріңіз — бәрін жаңадан толтырудың қажеті жоқ.",
  regeneratePlan: "Қайта жасап көру",
  planRetrying: "Қайта жасап жатырмыз…",
  planAutoRetrying: "Алғашқы жасау аяқталмады. Жоспарды қалпына келтіріп жатырмыз — нысанды қайта толтыру қажет емес.",
  planRetryUnavailable: "Қайта жасауды бастау мүмкін болмады. Интернетті тексеріп, тағы бір рет көріңіз — баптауларыңыз сақталды.",
  planStatusUnavailable: "Жоспардың дайындығын тексеріп жатырмыз",
  planStatusHint: "Жұмыс фонда жалғасуы мүмкін. Күйін жаңартыңыз — жаңа жоспар іске қосылмайды.",
  checkPlanStatus: "Күйін жаңарту",
  presentationTitle: "Презентация атауы",
  styleAnchor: "Ортақ стиль",
  styleAnchorPlaceholder: "Барлық презентацияға ортақ палитра және көрнекі тіл",
  slide: "Слайд",
  slideTitle: "Тақырып",
  slidePurpose: "Слайд мақсаты",
  slideBody: "Негізгі мазмұн",
  slideBullets: "Тезистер — әр жолға біреу",
  slideType: "Слайд түрі",
  visualIdea: "Слайдта нені көрсету керек",
  exactText: "Слайдтағы дәл мәтін — әр жолға бір элемент",
  facts: "Міндетті деректер — әр жолға біреу",
  imagePrompt: "Суретке арналған толық тапсырма",
  speakerNotes: "Мұғалім жазбалары",
  advancedPrompt: "ЖИ-ға тапсырма",
  moveUp: "Жоғары жылжыту",
  moveDown: "Төмен жылжыту",
  duplicate: "Көшірмесін жасау",
  deleteSlide: "Слайдты жою",
  addSlide: "Слайд қосу",
  unsaved: "Сақталмаған өзгерістер бар",
  saving: "Сақталуда…",
  saved: "Барлық өзгеріс сақталды",
  saveDraft: "Сақтау",
  calculateCost: "Құнын есептеу",
  costTitle: "Жасау құны",
  costPending: "Есептелуде…",
  costPerSlide: "бір слайд үшін",
  costTotal: "барлығы",
  coins: "монета",
  approveAndGenerate: "Жоспарды бекітіп, слайдтарды жасау",
  approvedPlanReadOnly: "Жоспар бекітілген, енді оны тек көруге болады.",
  backToEditor: "Слайдтарға оралу",
  approveTitle: "Слайдтарды жасауды бастаймыз ба?",
  approveClassicBody: "Жоспар бекітіледі. Жасалғаннан кейін мәтін мен безендіруді редакторда өзгертуге болады.",
  approveCreativeBody: "Жоспар бекітіліп, әр слайд тұтас салынады. Бір слайдты қайта жасау бөлек төленеді.",
  approve: "Бекітіп, бастау",
  revisionConflict: "Жоспар басқа қойындыда өзгерген. Жаңа нұсқаны жоғалтпау үшін бетті жаңартыңыз.",
  planValidation: "Барлық слайд атауын толтырыңыз. 4–30 слайд, әр слайдта 16 тармаққа және 20 факт не дәл мәтін жолына дейін рұқсат етіледі.",
  editorTitle: "Презентация",
  generationProgress: "Слайдтарды жасау",
  generatedOf: "дайын",
  jobQueued: "Кезекте",
  jobRunning: "Жасалуда",
  jobCompleted: "Жасау аяқталды",
  jobFailed: "Жасау кезінде қате болды",
  jobCompletedHint: "Слайдтар дайын. Жүктеу алдында тексеріп шығыңыз.",
  jobPartialHint: "Слайдтардың көбі дайын. Белгіленген слайдты ашып, қайта жасаңыз.",
  jobFailedHint: "Жоспарыңыз бен дайын слайдтар сақталды. Жасауды қайталауға болады.",
  jobCancelledHint: "Жасау тоқтатылды. Дайын болған слайдтар сақталды.",
  stopGeneration: "Қалғандарын тоқтату",
  stopping: "Тоқтатылуда…",
  refreshSafe: "Бетті жабуға болады — прогресс сақталады.",
  selectedSlide: "Таңдалған слайд",
  selectSlide: "Слайдты таңдаңыз",
  waitingSlide: "Бұл слайд әлі жасалып жатыр",
  failedSlide: "Бұл слайд дайын болмады",
  failedSlideHelp: "«Слайдты қайта жасау» түймесін басыңыз — қалған слайдтар өзгермейді.",
  retryFailedSlide: "Слайдты қайта жасау",
  openFailedSlide: "Дайын болмаған слайдты ашу",
  exportBlocked: "Барлық слайд дайын болғанда жүктеу қолжетімді болады.",
  generationNotFinished: "Слайдтардың жасалып біткенін күтіңіз.",
  previewUnavailable: "Алдын ала қарау әзірше қолжетімсіз",
  provisionalPreview: "Алдын ала нобай",
  layout: "Орналасу",
  layoutAuto: "Автоматты",
  layoutTitle: "Титулдық",
  layoutSection: "Бөлім",
  layoutContent: "Мәтін және тармақтар",
  layoutTitleBody: "Тақырып және мәтін",
  layoutTwoColumns: "Екі баған",
  layoutComparison: "Салыстыру",
  layoutTimeline: "Хронология",
  layoutProcess: "Процесс",
  layoutCards: "Карточкалар",
  layoutDiagram: "Сызба",
  layoutTable: "Кесте",
  layoutQuiz: "Сұрақ",
  layoutSummary: "Қорытынды",
  theme: "Түстер",
  themeSand: "Жылы",
  themeOcean: "Көк",
  themeForest: "Жасыл",
  themeNight: "Қою",
  body: "Негізгі мәтін",
  bullets: "Тезистер",
  notes: "Баяндамашы жазбалары",
  autosaveOn: "Өзгерістер автоматты түрде сақталады",
  saveError: "Өзгерістерді сақтау мүмкін болмады",
  versions: "Нұсқалар",
  version: "Нұсқа",
  activeVersion: "Таңдалды",
  useVersion: "Таңдау",
  regenerate: "Басқа нұсқа жасау",
  regenerating: "Іске қосылуда…",
  rebuildSlide: "Слайдты қайта жасау",
  regenerationInstruction: "Жаңа нұсқада нені өзгерту керек",
  regenerationInstructionPlaceholder: "Мысалы: мәтінді азайту, сызбаны үлкейту, түстерді тыныш ету…",
  acceptSlide: "Слайдты қабылдау",
  accepted: "Слайд қабылданды",
  qaTitle: "Мәтінді тексеру",
  qaClean: "Міндетті мәтін табылды, маңызды ескерту жоқ.",
  qaWarning: "Экспорт алдында осы бөлікті тексеріңіз",
  qaTextWarning: "Автоматты тексеру барлық мәтінді растай алмады. Слайдтағы жазуларды салыстырып тексеріңіз.",
  qaLayoutWarning: "Слайдтың экранға толық сыйғанын және ештеңе қиылмағанын тексеріңіз.",
  qaColorWarning: "Мәтіннің фонда анық оқылатынын тексеріңіз.",
  qaGenericWarning: "Автоматты тексеру қолмен қарап шығу керек орынды тапты.",
  exactTextWarning: "ЖИ қате жіберуі мүмкін — суреттегі мәтінді мұқият тексеріңіз.",
  export: "Экспорт",
  exportTitle: "Презентацияны жүктеу",
  exportSubtitle: "Қай файл керек екенін таңдаңыз.",
  exportFormat: "Формат",
  exportVariant: "Нұсқа",
  editablePptx: "Өңделетін PowerPoint",
  pixelPerfectPptx: "Дәл сәйкестік",
  imagePresentation: "PowerPoint",
  exportPowerPointDescription: "PowerPoint-та мәтінді, кестелерді және элементтерді өзгертуге болады.",
  exportCreativePowerPointDescription: "Слайдтардың көрінісі сақталады; әр слайд сурет күйінде қалады.",
  exportPdfLabel: "PDF",
  exportCreativeNotice: "Шығармашылық презентацияда әр слайд бір сурет болып қалады.",
  exportPdfNotice: "Жіберуге немесе басып шығаруға ыңғайлы. Слайдтарды өзгертуге болмайды.",
  exportSlidesNotReady: "Бір слайд әлі дайын емес. Слайдтарға оралып, қызыл белгісі бар слайдты ашыңыз да «Слайдты қайта жасау» түймесін басыңыз. Содан кейін қайта жүктеп көріңіз.",
  exportReturnToSlides: "Слайдтарға оралу",
  startExport: "Файлды дайындау",
  preparingExport: "Дайындалуда…",
  exportQueuedHint: "Файл дайындалып жатыр. Бұл терезені жабуға болады — дайын файл осында автоматты түрде шығады.",
  readyFiles: "Дайын файлдар",
  download: "Жүктеу",
  close: "Жабу",
  noExports: "Дайын файлдар әзірше жоқ",
  partialFailure: "Кейбір слайдтарды тексеру қажет",
  returnToPlan: "Жоспарға оралу",
  previous: "Артқа",
  next: "Келесі",
};

export function getPresentationCopy(language: Language): PresentationCopy {
  return language === "kk" ? kk : ru;
}
